"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient, type Session } from "@supabase/supabase-js";
import { ArrowLeft, Download, Image as ImageIcon, LoaderCircle, Sparkles, Video } from "lucide-react";

const db=createClient("https://kxuszpixwfecawdeqkrx.supabase.co","sb_publishable__auyhjNpepXiYdGV5HEJ_A_AGsPbBuS");
type Kind="image"|"video";
type StudioResponse={error?:string;request_id?:string;data?:{status?:string;message?:string;[key:string]:unknown};[key:string]:unknown};
function mediaUrls(value:unknown):string[]{const found:string[]=[];const visit=(v:unknown)=>{if(typeof v==="string"&&/^https?:\/\//i.test(v)&&/\.(png|jpe?g|webp|mp4|webm)(\?|$)/i.test(v))found.push(v);else if(Array.isArray(v))v.forEach(visit);else if(v&&typeof v==="object")Object.values(v as Record<string,unknown>).forEach(visit)};visit(value);return [...new Set(found)]}

export default function Studio(){
 const [session,setSession]=useState<Session|null>(null),[role,setRole]=useState(""),[kind,setKind]=useState<Kind>("image"),[prompt,setPrompt]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[media,setMedia]=useState<string[]>([]);
 useEffect(()=>{db.auth.getSession().then(async r=>{const s=r.data.session;setSession(s);if(s){const p=await db.from("english_profiles").select("role").eq("id",s.user.id).single();setRole(p.data?.role||"")}})},[]);
 async function invoke(body:Record<string,unknown>):Promise<StudioResponse>{const r=await db.functions.invoke("pixazo-studio",{body});if(r.error){let message=r.error.message;try{const details:unknown=await (r.error as {context?:Response}).context?.json();if(details&&typeof details==="object"&&"error" in details&&typeof (details as {error?:unknown}).error==="string")message=(details as {error:string}).error}catch{}throw new Error(message)}const data=(r.data||{}) as StudioResponse;if(data.error)throw new Error(data.error);return data}
 async function generate(e:FormEvent){e.preventDefault();if(!prompt.trim())return;setBusy(true);setError("");setMedia([]);try{let data=await invoke({type:kind,prompt});let urls=mediaUrls(data);let id=data.request_id;for(let i=0;!urls.length&&id&&i<18;i++){await new Promise(r=>setTimeout(r,5000));data=await invoke({action:"status",request_id:id});urls=mediaUrls(data);if(data.data?.status==="FAILED")throw new Error(data.data?.message||"Generation failed.")}if(!urls.length)throw new Error("Generation started but the media is not ready yet. Please try again shortly.");setMedia(urls)}catch(x){setError(x instanceof Error?x.message:"Generation failed.")}finally{setBusy(false)}}
 if(!session)return <main className="studio-page"><section className="studio-gate"><h1>Sign in required</h1><p>Sign in on English Study Co.Master before opening the teacher media studio.</p><a href="/">Return to website</a></section></main>;
 if(role!=="teacher")return <main className="studio-page"><section className="studio-gate"><h1>Teacher access only</h1><p>This studio creates learning images and videos for lessons and assignments.</p><a href="/">Return to website</a></section></main>;
 return <main className="studio-page"><header><a href="/" aria-label="Back"><ArrowLeft/></a><span><Sparkles/><b>AI Media Studio</b><small>Powered by Pixazo · tivalsdeveloper</small></span></header><section className="studio-card"><nav><button className={kind==="image"?"active":""} onClick={()=>setKind("image")}><ImageIcon/>Create image</button><button className={kind==="video"?"active":""} onClick={()=>setKind("video")}><Video/>Create video</button></nav><form onSubmit={generate}><label>Describe the {kind} for your English lesson<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={1500} rows={6} placeholder={kind==="image"?"Example: A colourful classroom poster explaining action verbs with simple examples":"Example: A short educational animation showing present, past and future tense"}/></label><small>{prompt.length}/1500</small><button disabled={busy||!prompt.trim()}>{busy?<><LoaderCircle className="spin"/>Creating…</>:<><Sparkles/>Generate {kind}</>}</button></form>{error&&<div className="studio-error">{error}</div>}{media.length>0&&<div className="studio-results">{media.map((url,i)=><article key={url}>{kind==="video"?<video src={url} controls playsInline/>:<img src={url} alt={"AI generated English lesson visual "+(i+1)}/>}<a href={url} target="_blank" rel="noreferrer" download><Download/>Download</a></article>)}</div>}<aside><b>Teacher tip</b><p>Use clear educational prompts and check every generated result before sharing it with students.</p></aside></section></main>
}
