"use client";
import {FormEvent,useEffect,useState} from "react";
import {createClient,type Session} from "@supabase/supabase-js";
import {Bookmark,BookOpen,CheckCircle,LogOut,Menu,MessageCircle,Monitor,Search,Send,Smartphone,Trash2,Users,Volume2,X} from "lucide-react";
const db=createClient("https://kxuszpixwfecawdeqkrx.supabase.co","sb_publishable__auyhjNpepXiYdGV5HEJ_A_AGsPbBuS");
type Profile={id:string;full_name:string;role:string};type Group={id:string;name:string;level:string;invite_code:string;teacher_id:string};type Msg={id:number;body:string;created_at:string;user_id:string;english_profiles?:{full_name:string}|null};type GroupLesson={id:string;title:string;content:string;level:string;created_at:string;teacher_id:string};
type DictEntry={word:string;phonetic?:string;phonetics?:{text?:string;audio?:string}[];meanings:{partOfSpeech:string;definitions:{definition:string;example?:string}[];synonyms?:string[];antonyms?:string[]}[]};
type SavedWord={id:string;word:string;phonetic:string;definition:string;created_at:string};
const lessons=[
 {level:"Beginner",title:"Greetings & introductions",summary:"Introduce yourself and greet people naturally.",time:"8 min",content:"Goal: Greet someone and introduce yourself.\n\nUseful words\n• Hello / Hi — a friendly greeting\n• Good morning — use before midday\n• My name is… — say your name\n• Nice to meet you — say this when meeting someone\n\nExample conversation\nA: Hello! My name is Lufuno. What is your name?\nB: Hi, Lufuno. I’m Thandi. Nice to meet you.\nA: Nice to meet you too.\n\nPractice\nWrite four sentences introducing yourself. Include your name, where you live, one thing you enjoy, and “Nice to meet you.”"},
 {level:"Elementary",title:"Everyday conversations",summary:"Ask useful questions for school and daily life.",time:"12 min",content:"Goal: Ask and answer common everyday questions.\n\nUseful questions\n• How are you today?\n• Where are you going?\n• What time does the lesson start?\n• Could you please help me?\n\nExample conversation\nA: Good morning. What time does the English lesson start?\nB: It starts at ten o’clock.\nA: Thank you. Could you please show me the classroom?\nB: Of course. Follow me.\n\nLanguage tip\nUse “please” and “thank you” to sound polite. Use “Could you…?” when requesting help.\n\nPractice\nCreate a six-line conversation between a student and a teacher. Use at least two questions."},
 {level:"Intermediate",title:"Speak with confidence",summary:"Build clear sentences and fluent responses.",time:"15 min",content:"Goal: Give longer, clearer answers without rushing.\n\nA strong answer has three parts:\n1. Answer the question directly.\n2. Give a reason.\n3. Add an example.\n\nQuestion: Why are you learning English?\nShort answer: For university.\nStrong answer: I am learning English because I want to communicate confidently at university. For example, I want to participate in class discussions and present my projects clearly.\n\nSpeaking tip\nPause between ideas. Words such as “because”, “for example”, “however” and “therefore” connect your thoughts.\n\nPractice\nAnswer this question in four sentences: What skill would you like to learn this year, and why?"}
];
const mindsetVideos=[
 {id:"Z53K13j2afE",title:"Concord errors",level:"English FAL · Grammar"},
 {id:"4UXbNbpCY6A",title:"South African English — FAL",level:"English FAL · Language"},
 {id:"aagAL9q4z2I",title:"Understanding cartoons",level:"English FAL · Visual literacy"},
 {id:"t62Q2CHI3QM",title:"Active voice, passive voice, antonyms and tag questions",level:"English FAL · Grammar"},
 {id:"hf_erpYjCgU",title:"Parts of speech",level:"English · Grammar"},
 {id:"36_ioED8-Bg",title:"More parts of speech",level:"English · Grammar"},
 {id:"3cpBNt0hwnU",title:"Getting full marks for comprehension",level:"English · Comprehension"},
 {id:"9No6EAXYKXc",title:"Reported speech",level:"English FAL · Grammar"},
 {id:"wGkIvhKXxus",title:"How to write an obituary",level:"English · Writing"},
 {id:"GPACl724A38",title:"Format of a formal letter",level:"English · Writing"},
 {id:"BeyfzaNlsig",title:"Instructions and directions",level:"English · Writing"},
 {id:"kSDWSTj8RoY",title:"Common exam mistakes — Paper 1",level:"English FAL · Exam preparation"}
];
export default function Home(){
 const[s,setS]=useState<Session|null>(null),[p,setP]=useState<Profile|null>(null),[groups,setGroups]=useState<Group[]>([]),[group,setGroup]=useState<Group|null>(null),[msgs,setMsgs]=useState<Msg[]>([]),[auth,setAuth]=useState(false),[signup,setSignup]=useState(false),[chat,setChat]=useState(false),[dictionary,setDictionary]=useState(false),[videoView,setVideoView]=useState<"landscape"|"portrait">("landscape"),[roomTab,setRoomTab]=useState<"lessons"|"chat">("lessons"),[menu,setMenu]=useState(false),[selectedLesson,setSelectedLesson]=useState<(typeof lessons)[number]|null>(null);
 useEffect(()=>{db.auth.getSession().then(r=>setS(r.data.session));const{data}=db.auth.onAuthStateChange((_e,x)=>setS(x));let v=localStorage.getItem("english-visit");if(!v){v=crypto.randomUUID();localStorage.setItem("english-visit",v)}db.from("english_visits").insert({session_id:v,path:location.pathname}).then(()=>{});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!s){setP(null);setGroups([]);return}db.from("english_profiles").select("*").eq("id",s.user.id).single().then(r=>setP(r.data));load()},[s]);
 useEffect(()=>{if(!group)return;const c=db.channel("chat-"+group.id).on("postgres_changes",{event:"INSERT",schema:"public",table:"english_messages",filter:"group_id=eq."+group.id},async e=>{const{data}=await db.from("english_messages").select("id,body,created_at,user_id,english_profiles(full_name)").eq("id",e.new.id).single();if(data)setMsgs(a=>[...a.filter(x=>x.id!==data.id),data as unknown as Msg])}).subscribe();return()=>{db.removeChannel(c)}},[group]);
 async function load(){const{data}=await db.from("english_groups").select("*").order("created_at",{ascending:false});setGroups(data||[])}
 async function open(g:Group,tab:"lessons"|"chat"="lessons"){if(!s){setAuth(true);return}setGroup(g);setRoomTab(tab);setChat(true);const{data}=await db.from("english_group_members").select("group_id").eq("group_id",g.id).eq("user_id",s.user.id).maybeSingle();if(!data&&g.teacher_id!==s.user.id)await db.from("english_group_members").insert({group_id:g.id,user_id:s.user.id});const r=await db.from("english_messages").select("id,body,created_at,user_id,english_profiles(full_name)").eq("group_id",g.id).order("created_at");setMsgs((r.data as unknown as Msg[])||[])}
 return <main><nav className="nav wrap"><a className="brand" href="#"><b>E</b><span>English Study<br/><strong>Co.Master</strong></span></a><div className={"links "+(menu?"show":"")}><a href="#lessons">Lessons</a><a href="#videos">Videos</a><a href="#community">Community</a><a href="#how">How it works</a></div><div className="actions">{s?<><span>Hi, {p?.full_name?.split(" ")[0]||"learner"}</span><button className="plain" onClick={()=>db.auth.signOut()}><LogOut/></button></>:<><button className="plain hide-mobile" onClick={()=>{setSignup(false);setAuth(true)}}>Sign in</button><button className="primary" onClick={()=>{setSignup(true);setAuth(true)}}>Start learning</button></>}<button className="plain hamburger" onClick={()=>setMenu(!menu)}><Menu/></button></div></nav>
 <section className="hero wrap"><div><label>✦ A FRIENDLY PLACE TO PRACTISE</label><h1>English grows<br/>when you <em>speak.</em></h1><p>Short, practical lessons and a supportive community—built for students who want to use English with confidence.</p><div className="hero-actions"><a className="primary" href="#lessons">Explore lessons →</a><button className="talk" onClick={()=>s?setChat(true):setAuth(true)}>▶ Join the conversation</button></div><small>Students and teachers are welcome</small></div><div className="visual"><i>Hello!</i><strong>Aa</strong><article><small>Today’s phrase</small><b>“How are you doing?”</b><small>A friendly way to ask how someone is.</small></article><aside><CheckCircle/> Lesson complete</aside></div></section>
 <section id="lessons" className="lessons"><div className="wrap"><header><div><label>LEARN AT YOUR PACE</label><h2>Start with a short lesson</h2></div><p>Clear explanations, useful examples and a practice task in every lesson.</p></header><div className="cards">{lessons.map((l,i)=><article className={"c"+i} key={l.level}><div><span>0{i+1}</span><small>{l.time}</small></div><label>{l.level}</label><h3>{l.title}</h3><p>{l.summary}</p><button onClick={()=>setSelectedLesson(l)}>Open lesson ↗</button></article>)}</div></div></section>
 <section id="videos" className="video-lessons"><div className="wrap"><header><div><label>WATCH AND LEARN</label><h2>English lessons from Mindset Learn</h2></div><a href="https://www.youtube.com/@MindsetLearn" target="_blank" rel="noreferrer">Visit Mindset Learn on YouTube ↗</a></header><div className="video-tools" aria-label="Video orientation"><span>Video view</span><div><button className={videoView==="landscape"?"active":""} onClick={()=>setVideoView("landscape")}><Monitor/> Landscape</button><button className={videoView==="portrait"?"active":""} onClick={()=>setVideoView("portrait")}><Smartphone/> Portrait</button></div></div><div className={"video-grid "+videoView}>{mindsetVideos.map(video=><article key={video.id}><div className="video-frame"><iframe src={"https://www.youtube-nocookie.com/embed/"+video.id} title={video.title} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div><small>{video.level}</small><h3>{video.title}</h3></article>)}</div><p className="video-credit">Videos are provided by Mindset Learn through YouTube. English Study Co.Master does not own these videos.</p></div></section>
 <section id="community" className="community wrap"><div><label>PRACTISE TOGETHER</label><h2>A safe place to try, ask and improve.</h2><p>Mistakes are welcome. Create or join a group, open full lessons and learn through conversation.</p><Feature icon={<MessageCircle/>} title="Live group chat" text="Practise with students and teachers in real time."/><Feature icon={<Users/>} title="Learning groups" text="Create a group, invite learners and share lessons."/></div><div className="panel"><header><b>● Community groups</b>{s&&<NewGroup userId={s.user.id} add={g=>setGroups(a=>[g,...a.filter(x=>x.id!==g.id)])} remove={id=>setGroups(a=>a.filter(x=>x.id!==id))}/>}</header>{!s?<Empty title="Sign in to join the conversation" text="Accounts keep every group chat members-only." action={()=>setAuth(true)}/>:groups.length?<div className="group-list">{groups.map(g=><button key={g.id} onClick={()=>open(g)}><b>{g.name[0]}</b><span><strong>{g.name}</strong><small>{g.level} · Code {g.invite_code}</small></span><i>→</i></button>)}</div>:<Empty title="No groups yet" text="Create the first learning group."/>}</div></section>
 <section id="how" className="steps"><div className="wrap"><label>THREE SIMPLE STEPS</label><h2>Begin your English journey</h2><div>{[["1","Create your profile","Register as a student or teacher and verify your email."],["2","Learn something useful","Open a practical lesson made for your level."],["3","Use English together","Join a group and practise in the live chat."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
 <footer><div className="wrap"><span>English Study <b>Co.Master</b></span><i>Learn English. Teach with confidence. Grow together.</i><strong>Powered by tivalsdeveloper</strong></div></footer>
 <div className="utility-launchers"><button className="dictionary-launch" aria-label="Open English dictionary" onClick={()=>setDictionary(true)}><BookOpen/><span>Dictionary</span></button>{s&&!chat&&<button className="chat-launch" aria-label="Open group chat" onClick={()=>group?open(group,"chat"):groups[0]?open(groups[0],"chat"):document.getElementById("community")?.scrollIntoView()}><MessageCircle/><span>Chat</span></button>}</div>{selectedLesson&&<div className="shade"><section className="lesson-modal"><button className="close" onClick={()=>setSelectedLesson(null)}><X/></button><label>{selectedLesson.level} · {selectedLesson.time}</label><h2>{selectedLesson.title}</h2><p>{selectedLesson.content}</p><button className="primary" onClick={()=>setSelectedLesson(null)}>Finish lesson</button></section></div>}{auth&&<Auth signup={signup} change={setSignup} close={()=>setAuth(false)}/>} {chat&&<Chat group={group} msgs={msgs} s={s} profile={p} initialTab={roomTab} close={()=>setChat(false)}/>} {dictionary&&<Dictionary session={s} signIn={()=>{setDictionary(false);setSignup(false);setAuth(true)}} close={()=>setDictionary(false)}/>}</main>}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="feature">{icon}<span><b>{title}</b><small>{text}</small></span></div>}
function Empty({title,text,action}:{title:string;text:string;action?:()=>void}){return <div className="empty"><Users/><h3>{title}</h3><p>{text}</p>{action&&<button className="primary" onClick={action}>Sign in to continue</button>}</div>}
function Auth({signup,change,close}:{signup:boolean;change:(x:boolean)=>void;close:()=>void}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(""),[verify,setVerify]=useState(false),[email,setEmail]=useState(""),[code,setCode]=useState(["","","","","","","",""]),[wait,setWait]=useState(60);
 useEffect(()=>{if(!verify||wait<=0)return;const timer=setInterval(()=>setWait(value=>value-1),1000);return()=>clearInterval(timer)},[verify,wait]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget),mail=String(f.get("email")),password=String(f.get("password"));setEmail(mail);const r=signup?await db.auth.signUp({email:mail,password,options:{data:{full_name:String(f.get("name")),username:String(f.get("username")),role:String(f.get("role"))}}}):await db.auth.signInWithPassword({email:mail,password});if(r.error)setError(r.error.message);else if(signup){setVerify(true);setWait(60)}else close();setBusy(false)}
 function digit(i:number,value:string){const d=value.replace(/\D/g,"").slice(-1),next=[...code];next[i]=d;setCode(next);if(d)(document.getElementById("otp-"+(i+1)) as HTMLInputElement|null)?.focus()}
 async function confirm(){const token=code.join("");if(token.length!==8){setError("Enter the complete eight-digit code.");return}setBusy(true);setError("");const{error}=await db.auth.verifyOtp({email,token,type:"email"});if(error)setError(error.message);else close();setBusy(false)}
 async function resend(){setBusy(true);setError("");const{error}=await db.auth.resend({type:"signup",email});if(error)setError(error.message);else setWait(60);setBusy(false)}
 return <div className="shade"><section className="auth"><button className="close" onClick={close}><X/></button><div className="logo">E</div>{verify?<div className="verify"><h2>Enter verification code</h2><p>We sent an eight-digit code to <b>{email}</b>. It expires shortly.</p><div className="otp">{code.map((d,i)=><input id={"otp-"+i} key={i} value={d} inputMode="numeric" maxLength={1} aria-label={"Digit "+(i+1)} onChange={e=>digit(i,e.target.value)} onKeyDown={e=>{if(e.key==="Backspace"&&!d)(document.getElementById("otp-"+(i-1)) as HTMLInputElement|null)?.focus()}}/>)}</div>{error&&<div className="error">{error}</div>}<button className="primary verify-btn" disabled={busy} onClick={confirm}>{busy?"Checking…":"Verify account"}</button><button className="resend" disabled={busy||wait>0} onClick={resend}>{wait>0?"Resend code in "+wait+"s":"Resend code"}</button><button className="wrong" onClick={()=>{setVerify(false);setCode(["","","","","","","",""]);setError("")}}>Use a different email</button></div>:<><h2>{signup?"Create your account":"Welcome back"}</h2><p>{signup?"Join students and teachers learning together.":"Continue your English journey."}</p><form onSubmit={submit}>{signup&&<><label>Full name<input required name="name" placeholder="Your full name"/></label><label>Username<input required name="username" pattern="[A-Za-z0-9_]{3,24}" placeholder="e.g. lufuno_07"/></label><label>I am a<select name="role"><option value="student">Student</option><option value="teacher">Teacher</option></select></label></>}<label>Email address<input required type="email" name="email" placeholder="you@example.com"/></label><label>Password<input required type="password" minLength={8} name="password" placeholder="At least 8 characters"/></label>{error&&<div className="error">{error}</div>}<button disabled={busy} className="primary">{busy?"Please wait…":signup?"Create account":"Sign in"}</button></form><small>{signup?"Already registered?":"New here?"} <button onClick={()=>change(!signup)}>{signup?"Sign in":"Create an account"}</button></small></>}</section></div>
}
function Dictionary({session,signIn,close}:{session:Session|null;signIn:()=>void;close:()=>void}){
 const[query,setQuery]=useState(""),[entries,setEntries]=useState<DictEntry[]>([]),[saved,setSaved]=useState<SavedWord[]>([]),[tab,setTab]=useState<"search"|"saved">("search"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!session)return;db.from("english_saved_words").select("*").eq("user_id",session.user.id).order("created_at",{ascending:false}).then(r=>setSaved((r.data as SavedWord[])||[]))},[session]);
 async function findWord(word:string){if(!word.trim())return;setBusy(true);setError("");setEntries([]);try{const response=await fetch("/.netlify/functions/dictionary?word="+encodeURIComponent(word.trim()));const type=response.headers.get("content-type")||"";if(!type.includes("application/json"))throw new Error("The dictionary service is not responding correctly. Please try again.");const payload=await response.json() as DictEntry[]|{error?:string};if(!response.ok)throw new Error(!Array.isArray(payload)&&payload.error||"We could not find that word. Check the spelling and try again.");if(!Array.isArray(payload))throw new Error("The dictionary returned an unexpected response.");setEntries(payload)}catch(problem){setError(problem instanceof Error?problem.message:"Dictionary is unavailable. Try again shortly.")}finally{setBusy(false)}}
 function lookup(e:FormEvent){e.preventDefault();void findWord(query)}
 function audio(){const source=entries.flatMap(x=>x.phonetics||[]).find(x=>x.audio)?.audio;if(source)new Audio(source.startsWith("//")?"https:"+source:source).play()}
 async function save(){if(!session){signIn();return}const entry=entries[0],definition=entry?.meanings[0]?.definitions[0]?.definition;if(!entry||!definition)return;const item={user_id:session.user.id,word:entry.word.toLowerCase(),phonetic:entry.phonetic||entry.phonetics?.find(x=>x.text)?.text||"",definition};const{data,error:problem}=await db.from("english_saved_words").upsert(item,{onConflict:"user_id,word"}).select().single();if(problem){setError(problem.message);return}setSaved(a=>[data as SavedWord,...a.filter(x=>x.word!==item.word)])}
 async function remove(item:SavedWord){setSaved(a=>a.filter(x=>x.id!==item.id));const{error:problem}=await db.from("english_saved_words").delete().eq("id",item.id);if(problem){setSaved(a=>[item,...a]);setError(problem.message)}}
 const entry=entries[0],isSaved=entry&&saved.some(x=>x.word===entry.word.toLowerCase());
 return <div className="shade dictionary-shade"><section className="dictionary"><header><span><BookOpen/><b>English dictionary</b></span><button aria-label="Close dictionary" onClick={close}><X/></button></header><nav><button className={tab==="search"?"active":""} onClick={()=>setTab("search")}><Search/> Search</button><button className={tab==="saved"?"active":""} onClick={()=>setTab("saved")}><Bookmark/> Saved words</button></nav>{tab==="search"?<div className="dictionary-body"><form onSubmit={lookup}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Type an English word…" autoFocus/><button disabled={busy} aria-label="Search"><Search/></button></form>{busy&&<p className="dict-status">Looking up “{query}”…</p>}{error&&<div className="error">{error}</div>}{entry&&<article className="word-result"><div className="word-heading"><div><h2>{entry.word}</h2><span>{entry.phonetic||entry.phonetics?.find(x=>x.text)?.text}</span></div><div>{entry.phonetics?.some(x=>x.audio)&&<button aria-label="Hear pronunciation" onClick={audio}><Volume2/></button>}<button className={isSaved?"saved":""} aria-label="Save word" disabled={!!isSaved} onClick={save}><Bookmark/>{isSaved?"Saved":"Save"}</button></div></div>{entry.meanings.slice(0,4).map((meaning,i)=><section key={meaning.partOfSpeech+i}><h3>{meaning.partOfSpeech}</h3><ol>{meaning.definitions.slice(0,3).map((definition,j)=><li key={j}><p>{definition.definition}</p>{definition.example&&<blockquote>“{definition.example}”</blockquote>}</li>)}</ol>{meaning.synonyms?.length?<p className="word-list"><b>Synonyms:</b> {meaning.synonyms.slice(0,6).join(", ")}</p>:null}{meaning.antonyms?.length?<p className="word-list"><b>Antonyms:</b> {meaning.antonyms.slice(0,6).join(", ")}</p>:null}</section>)}</article>}{!busy&&!entry&&!error&&<div className="dict-welcome"><BookOpen/><h2>Discover a new word</h2><p>Search for definitions, examples, pronunciation, synonyms and antonyms.</p></div>}</div>:<div className="saved-words">{!session?<div className="dict-welcome"><Bookmark/><h2>Build your vocabulary</h2><p>Sign in to save words and return to them anytime.</p><button className="primary" onClick={signIn}>Sign in to save words</button></div>:saved.length?saved.map(item=><article key={item.id}><button className="saved-word" onClick={()=>{setQuery(item.word);setTab("search");void findWord(item.word)}}><b>{item.word}</b><small>{item.phonetic}</small><p>{item.definition}</p></button><button className="delete-word" aria-label={"Remove "+item.word} onClick={()=>remove(item)}><Trash2/></button></article>):<div className="dict-welcome"><Bookmark/><h2>No saved words yet</h2><p>Search for a word, then tap Save to add it here.</p></div>}</div>}</section></div>
}
function NewGroup({userId,add,remove}:{userId:string;add:(group:Group)=>void;remove:(id:string)=>void}){const[show,setShow]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),id=crypto.randomUUID(),invite_code=crypto.randomUUID().replaceAll("-","").slice(0,8).toUpperCase(),group:Group={id,teacher_id:userId,name:String(f.get("name")).trim(),level:String(f.get("level")),invite_code};add(group);setShow(false);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);void(async()=>{try{const{error}=await db.from("english_groups").insert({...group,description:""}).abortSignal(controller.signal);clearTimeout(timer);if(error){remove(id);alert("The group was not saved: "+error.message)}}catch{clearTimeout(timer);remove(id);alert("The group was not saved. Check your internet connection and try again.")}})()}return <><button className="new" onClick={()=>setShow(true)}>+ New group</button>{show&&<div className="mini"><form onSubmit={submit}><b>Create a group</b><input required minLength={3} maxLength={80} name="name" placeholder="Group name"/><select name="level">{["Beginner","Elementary","Intermediate","Upper-intermediate","Advanced"].map(x=><option key={x}>{x}</option>)}</select><div><button type="button" onClick={()=>setShow(false)}>Cancel</button><button className="primary">Create</button></div></form></div>}</>}
function Chat({group,msgs,s,profile,initialTab,close}:{group:Group|null;msgs:Msg[];s:Session|null;profile:Profile|null;initialTab:"lessons"|"chat";close:()=>void}){
 const[body,setBody]=useState(""),[tab,setTab]=useState<"lessons"|"chat">(initialTab),[items,setItems]=useState<GroupLesson[]>([]),[posting,setPosting]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!group)return;db.from("english_lessons").select("*").eq("group_id",group.id).order("created_at",{ascending:false}).then(r=>setItems((r.data as GroupLesson[])||[]))},[group]);
 async function send(e:FormEvent){e.preventDefault();if(!group||!s||!body.trim())return;const v=body.trim();setBody("");await db.from("english_messages").insert({group_id:group.id,user_id:s.user.id,body:v})}
 async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!group||!s)return;setError("");const f=new FormData(e.currentTarget);const{data,error:problem}=await db.from("english_lessons").insert({group_id:group.id,teacher_id:s.user.id,title:String(f.get("title")),level:String(f.get("level")),content:String(f.get("content"))}).select().single();if(problem){setError(problem.message);return}setItems(a=>[data as GroupLesson,...a]);setPosting(false)}
 const canPost=profile?.role==="teacher"&&group?.teacher_id===s?.user.id;
 return <aside className="chat room"><header><span><b>{group?.name||"Community"}</b><small>{group?.level||"Choose a group"}</small></span><button onClick={close}><X/></button></header>{group&&<nav className="room-tabs"><button className={tab==="lessons"?"active":""} onClick={()=>setTab("lessons")}><BookOpen/> Lessons</button><button className={tab==="chat"?"active":""} onClick={()=>setTab("chat")}><MessageCircle/> Chat</button></nav>}
 {tab==="lessons"?<div className="lesson-room">{canPost&&<button className="primary post-button" onClick={()=>setPosting(true)}>+ Post new lesson</button>}{!group?<Empty title="Choose a group" text="Select a community group to begin."/>:items.length?<div className="published-lessons">{items.map(x=><article key={x.id}><label>{x.level}</label><h3>{x.title}</h3><small>{new Date(x.created_at).toLocaleDateString()}</small><p>{x.content}</p></article>)}</div>:<Empty title="No lessons yet" text={canPost?"Post the first complete lesson for this group.":"Your teacher has not posted a lesson yet."}/>}</div>:<><div className="messages">{!group?<Empty title="Choose a group" text="Select a community group to begin."/>:msgs.length?msgs.map(m=><article className={m.user_id===s?.user.id?"mine":""} key={m.id}><small>{m.english_profiles?.full_name||"Learner"}</small><p>{m.body}</p><time>{new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></article>):<Empty title="No messages yet" text="Say hello and begin the conversation!"/>}</div>{group&&<form onSubmit={send}><input value={body} onChange={e=>setBody(e.target.value)} maxLength={1500} placeholder="Write a message…"/><button><Send/></button></form>}</>}
 {posting&&<div className="lesson-editor"><form onSubmit={publish}><h3>Post a new lesson</h3><label>Lesson title<input required name="title" minLength={3} maxLength={120} placeholder="e.g. Ordering food politely"/></label><label>Level<select name="level" defaultValue={group?.level}>{["Beginner","Elementary","Intermediate","Upper-intermediate","Advanced"].map(x=><option key={x}>{x}</option>)}</select></label><label>Lesson content<textarea required name="content" minLength={20} maxLength={12000} rows={10} placeholder="Add the explanation, examples, vocabulary and practice task…"/></label>{error&&<div className="error">{error}</div>}<div><button type="button" onClick={()=>setPosting(false)}>Cancel</button><button className="primary">Publish lesson</button></div></form></div>}
 </aside>}
